{ album:
  { album_type: 'single',
    artists: [ [Object] ],
    available_markets:
     [ 'AD',
       'AE',
       'AR',
       'AT',
       'AU',
       'BE',
       'BG',
       'BH',
       'BO',
       'BR',
       'CA',
       'CH',
       'CL',
       'CO',
       'CR',
       'CY',
       'CZ',
       'DE',
       'DK',
       'DO',
       'DZ',
       'EC',
       'EE',
       'EG',
       'ES',
       'FI',
       'FR',
       'GB',
       'GR',
       'GT',
       'HK',
       'HN',
       'HU',
       'ID',
       'IE',
       'IL',
       'IN',
       'IS',
       'IT',
       'JO',
       'JP',
       'KW',
       'LB',
       'LI',
       'LT',
       'LU',
       'LV',
       'MA',
       'MC',
       'MT',
       'MX',
       'MY',
       'NI',
       'NL',
       'NO',
       'NZ',
       'OM',
       'PA',
       'PE',
       'PH',
       'PL',
       'PS',
       'PT',
       'PY',
       'QA',
       'RO',
       'SA',
       'SE',
       'SG',
       'SK',
       'SV',
       'TH',
       'TN',
       'TR',
       'TW',
       'US',
       'UY',
       'VN',
       'ZA' ],
    external_urls:
     { spotify: 'https://open.spotify.com/album/3Rl6D2dD5fLEZ6NICHc6Ak' },
    href: 'https://api.spotify.com/v1/albums/3Rl6D2dD5fLEZ6NICHc6Ak',
    id: '3Rl6D2dD5fLEZ6NICHc6Ak',
    images: [ [Object], [Object], [Object] ],
    name: 'Load Up The Bases (The Baseball Song) - Single',
    release_date: '2013-10-24',
    release_date_precision: 'day',
    total_tracks: 1,
    type: 'album',
    uri: 'spotify:album:3Rl6D2dD5fLEZ6NICHc6Ak' },
 artists:
  [ { external_urls: [Object],
      href: 'https://api.spotify.com/v1/artists/0Wj5XD3AesB8FXsf6tUnBh',
      id: '0Wj5XD3AesB8FXsf6tUnBh',
      name: 'Whiskey Falls',
      type: 'artist',
      uri: 'spotify:artist:0Wj5XD3AesB8FXsf6tUnBh' } ],
 available_markets:
  [ 'AD',
    'AE',
    'AR',
    'AT',
    'AU',
    'BE',
    'BG',
    'BH',
    'BO',
    'BR',
    'CA',
    'CH',
    'CL',
    'CO',
    'CR',
    'CY',
    'CZ',
    'DE',
    'DK',
    'DO',
    'DZ',
    'EC',
    'EE',
    'EG',
    'ES',
    'FI',
    'FR',
    'GB',
    'GR',
    'GT',
    'HK',
    'HN',
    'HU',
    'ID',
    'IE',
    'IL',
    'IN',
    'IS',
    'IT',
    'JO',
    'JP',
    'KW',
    'LB',
    'LI',
    'LT',
    'LU',
    'LV',
    'MA',
    'MC',
    'MT',
    'MX',
    'MY',
    'NI',
    'NL',
    'NO',
    'NZ',
    'OM',
    'PA',
    'PE',
    'PH',
    'PL',
    'PS',
    'PT',
    'PY',
    'QA',
    'RO',
    'SA',
    'SE',
    'SG',
    'SK',
    'SV',
    'TH',
    'TN',
    'TR',
    'TW',
    'US',
    'UY',
    'VN',
    'ZA' ],
 disc_number: 1,
 duration_ms: 218440,
 explicit: false,
 external_ids: { isrc: 'QMW7N1100343' },
 external_urls:
  { spotify: 'https://open.spotify.com/track/1Tb0zipKYo8xNiaX9e7xAi' },
 href: 'https://api.spotify.com/v1/tracks/1Tb0zipKYo8xNiaX9e7xAi',
 id: '1Tb0zipKYo8xNiaX9e7xAi',
 is_local: false,
 name: 'Load Up The Bases (The Baseball Song)',
 popularity: 38,
 preview_url:
  'https://p.scdn.co/mp3-preview/dcdd83f4fd47d287fbd44f0791b0080d5ca6f4f2?cid=7c1864d3818042229a1abd512e54cbf8',
 track_number: 1,
 type: 'track',
 uri: 'spotify:track:1Tb0zipKYo8xNiaX9e7xAi' }
{ album:
  { album_type: 'single',
    artists: [ [Object] ],
    available_markets:
     [ 'AD',
       'AE',
       'AR',
       'AT',
       'AU',
       'BE',
       'BG',
       'BH',
       'BO',
       'BR',
       'CA',
       'CH',
       'CL',
       'CO',
       'CR',
       'CY',
       'CZ',
       'DE',
       'DK',
       'DO',
       'DZ',
       'EC',
       'EE',
       'EG',
       'ES',
       'FI',
       'FR',
       'GB',
       'GR',
       'GT',
       'HK',
       'HN',
       'HU',
       'ID',
       'IE',
       'IL',
       'IN',
       'IS',
       'IT',
       'JO',
       'JP',
       'KW',
       'LB',
       'LI',
       'LT',
       'LU',
       'LV',
       'MA',
       'MC',
       'MT',
       'MX',
       'MY',
       'NI',
       'NL',
       'NO',
       'NZ',
       'OM',
       'PA',
       'PE',
       'PH',
       'PL',
       'PS',
       'PT',
       'PY',
       'QA',
       'RO',
       'SA',
       'SE',
       'SG',
       'SK',
       'SV',
       'TH',
       'TN',
       'TR',
       'TW',
       'US',
       'UY',
       'VN',
       'ZA' ],
    external_urls:
     { spotify: 'https://open.spotify.com/album/0gCtKStUUjoiltLXs7c7Xf' },
    href: 'https://api.spotify.com/v1/albums/0gCtKStUUjoiltLXs7c7Xf',
    id: '0gCtKStUUjoiltLXs7c7Xf',
    images: [ [Object], [Object], [Object] ],
    name: 'Road To Dallas',
    release_date: '2016-03-26',
    release_date_precision: 'day',
    total_tracks: 1,
    type: 'album',
    uri: 'spotify:album:0gCtKStUUjoiltLXs7c7Xf' },
 artists:
  [ { external_urls: [Object],
      href: 'https://api.spotify.com/v1/artists/0Wj5XD3AesB8FXsf6tUnBh',
      id: '0Wj5XD3AesB8FXsf6tUnBh',
      name: 'Whiskey Falls',
      type: 'artist',
      uri: 'spotify:artist:0Wj5XD3AesB8FXsf6tUnBh' } ],
 available_markets:
  [ 'AD',
    'AE',
    'AR',
    'AT',
    'AU',
    'BE',
    'BG',
    'BH',
    'BO',
    'BR',
    'CA',
    'CH',
    'CL',
    'CO',
    'CR',
    'CY',
    'CZ',
    'DE',
    'DK',
    'DO',
    'DZ',
    'EC',
    'EE',
    'EG',
    'ES',
    'FI',
    'FR',
    'GB',
    'GR',
    'GT',
    'HK',
    'HN',
    'HU',
    'ID',
    'IE',
    'IL',
    'IN',
    'IS',
    'IT',
    'JO',
    'JP',
    'KW',
    'LB',
    'LI',
    'LT',
    'LU',
    'LV',
    'MA',
    'MC',
    'MT',
    'MX',
    'MY',
    'NI',
    'NL',
    'NO',
    'NZ',
    'OM',
    'PA',
    'PE',
    'PH',
    'PL',
    'PS',
    'PT',
    'PY',
    'QA',
    'RO',
    'SA',
    'SE',
    'SG',
    'SK',
    'SV',
    'TH',
    'TN',
    'TR',
    'TW',
    'US',
    'UY',
    'VN',
    'ZA' ],
 disc_number: 1,
 duration_ms: 217142,
 explicit: false,
 external_ids: { isrc: 'USDXS1600048' },
 external_urls:
  { spotify: 'https://open.spotify.com/track/4OO01LeQ4K0Q159qLuCNyC' },
 href: 'https://api.spotify.com/v1/tracks/4OO01LeQ4K0Q159qLuCNyC',
 id: '4OO01LeQ4K0Q159qLuCNyC',
 is_local: false,
 name: 'Road To Dallas',
 popularity: 7,
 preview_url:
  'https://p.scdn.co/mp3-preview/a4f1bc3edf8e20beb445d95d4e386e55f0d498b9?cid=7c1864d3818042229a1abd512e54cbf8',
 track_number: 1,
 type: 'track',
 uri: 'spotify:track:4OO01LeQ4K0Q159qLuCNyC' }
{ album:
  { album_type: 'compilation',
    artists: [ [Object] ],
    available_markets:
     [ 'AD',
       'AE',
       'AR',
       'AT',
       'AU',
       'BE',
       'BG',
       'BH',
       'BO',
       'BR',
       'CA',
       'CH',
       'CL',
       'CO',
       'CR',
       'CY',
       'CZ',
       'DE',
       'DK',
       'DO',
       'DZ',
       'EC',
       'EE',
       'EG',
       'ES',
       'FI',
       'FR',
       'GB',
       'GR',
       'GT',
       'HK',
       'HN',
       'HU',
       'ID',
       'IE',
       'IL',
       'IN',
       'IS',
       'IT',
       'JO',
       'JP',
       'KW',
       'LB',
       'LI',
       'LT',
       'LU',
       'LV',
       'MA',
       'MC',
       'MT',
       'MX',
       'MY',
       'NI',
       'NL',
       'NO',
       'NZ',
       'OM',
       'PA',
       'PE',
       'PH',
       'PL',
       'PS',
       'PT',
       'PY',
       'QA',
       'RO',
       'SA',
       'SE',
       'SG',
       'SK',
       'SV',
       'TH',
       'TN',
       'TR',
       'TW',
       'US',
       'UY',
       'VN',
       'ZA' ],
    external_urls:
     { spotify: 'https://open.spotify.com/album/2Qvke2IWoAzDuMn31klEGL' },
    href: 'https://api.spotify.com/v1/albums/2Qvke2IWoAzDuMn31klEGL',
    id: '2Qvke2IWoAzDuMn31klEGL',
    images: [ [Object], [Object], [Object] ],
    name:
     'Bristol Nights: The Official Music Of Bristol Motor Speedway',
    release_date: '2009-07-28',
    release_date_precision: 'day',
    total_tracks: 12,
    type: 'album',
    uri: 'spotify:album:2Qvke2IWoAzDuMn31klEGL' },
 artists:
  [ { external_urls: [Object],
      href: 'https://api.spotify.com/v1/artists/0Wj5XD3AesB8FXsf6tUnBh',
      id: '0Wj5XD3AesB8FXsf6tUnBh',
      name: 'Whiskey Falls',
      type: 'artist',
      uri: 'spotify:artist:0Wj5XD3AesB8FXsf6tUnBh' } ],
 available_markets:
  [ 'AD',
    'AE',
    'AR',
    'AT',
    'AU',
    'BE',
    'BG',
    'BH',
    'BO',
    'BR',
    'CA',
    'CH',
    'CL',
    'CO',
    'CR',
    'CY',
    'CZ',
    'DE',
    'DK',
    'DO',
    'DZ',
    'EC',
    'EE',
    'EG',
    'ES',
    'FI',
    'FR',
    'GB',
    'GR',
    'GT',
    'HK',
    'HN',
    'HU',
    'ID',
    'IE',
    'IL',
    'IN',
    'IS',
    'IT',
    'JO',
    'JP',
    'KW',
    'LB',
    'LI',
    'LT',
    'LU',
    'LV',
    'MA',
    'MC',
    'MT',
    'MX',
    'MY',
    'NI',
    'NL',
    'NO',
    'NZ',
    'OM',
    'PA',
    'PE',
    'PH',
    'PL',
    'PS',
    'PT',
    'PY',
    'QA',
    'RO',
    'SA',
    'SE',
    'SG',
    'SK',
    'SV',
    'TH',
    'TN',
    'TR',
    'TW',
    'US',
    'UY',
    'VN',
    'ZA' ],
 disc_number: 1,
 duration_ms: 189124,
 explicit: false,
 external_ids: { isrc: 'US-KMZ-09-50025' },
 external_urls:
  { spotify: 'https://open.spotify.com/track/3oA0pVQZ1mNBLBiN4QbN9t' },
 href: 'https://api.spotify.com/v1/tracks/3oA0pVQZ1mNBLBiN4QbN9t',
 id: '3oA0pVQZ1mNBLBiN4QbN9t',
 is_local: false,
 name: 'Tailgate Party',
 popularity: 7,
 preview_url:
  'https://p.scdn.co/mp3-preview/f9ad7588d4aab2e80fc2054dc5950724a53daffe?cid=7c1864d3818042229a1abd512e54cbf8',
 track_number: 6,
 type: 'track',
 uri: 'spotify:track:3oA0pVQZ1mNBLBiN4QbN9t' }
{ album:
  { album_type: 'compilation',
    artists: [ [Object] ],
    available_markets:
     [ 'AD',
       'AE',
       'AR',
       'AT',
       'AU',
       'BE',
       'BG',
       'BH',
       'BO',
       'BR',
       'CA',
       'CH',
       'CL',
       'CO',
       'CR',
       'CY',
       'CZ',
       'DE',
       'DK',
       'DO',
       'DZ',
       'EC',
       'EE',
       'EG',
       'ES',
       'FI',
       'FR',
       'GB',
       'GR',
       'GT',
       'HK',
       'HN',
       'HU',
       'ID',
       'IE',
       'IL',
       'IN',
       'IS',
       'IT',
       'JO',
       'JP',
       'KW',
       'LB',
       'LI',
       'LT',
       'LU',
       'LV',
       'MA',
       'MC',
       'MT',
       'MX',
       'MY',
       'NI',
       'NL',
       'NO',
       'NZ',
       'OM',
       'PA',
       'PE',
       'PH',
       'PL',
       'PS',
       'PT',
       'PY',
       'QA',
       'RO',
       'SA',
       'SE',
       'SG',
       'SK',
       'SV',
       'TH',
       'TN',
       'TR',
       'TW',
       'US',
       'UY',
       'VN',
       'ZA' ],
    external_urls:
     { spotify: 'https://open.spotify.com/album/2Qvke2IWoAzDuMn31klEGL' },
    href: 'https://api.spotify.com/v1/albums/2Qvke2IWoAzDuMn31klEGL',
    id: '2Qvke2IWoAzDuMn31klEGL',
    images: [ [Object], [Object], [Object] ],
    name:
     'Bristol Nights: The Official Music Of Bristol Motor Speedway',
    release_date: '2009-07-28',
    release_date_precision: 'day',
    total_tracks: 12,
    type: 'album',
    uri: 'spotify:album:2Qvke2IWoAzDuMn31klEGL' },
 artists:
  [ { external_urls: [Object],
      href: 'https://api.spotify.com/v1/artists/0Wj5XD3AesB8FXsf6tUnBh',
      id: '0Wj5XD3AesB8FXsf6tUnBh',
      name: 'Whiskey Falls',
      type: 'artist',
      uri: 'spotify:artist:0Wj5XD3AesB8FXsf6tUnBh' } ],
 available_markets:
  [ 'AD',
    'AE',
    'AR',
    'AT',
    'AU',
    'BE',
    'BG',
    'BH',
    'BO',
    'BR',
    'CA',
    'CH',
    'CL',
    'CO',
    'CR',
    'CY',
    'CZ',
    'DE',
    'DK',
    'DO',
    'DZ',
    'EC',
    'EE',
    'EG',
    'ES',
    'FI',
    'FR',
    'GB',
    'GR',
    'GT',
    'HK',
    'HN',
    'HU',
    'ID',
    'IE',
    'IL',
    'IN',
    'IS',
    'IT',
    'JO',
    'JP',
    'KW',
    'LB',
    'LI',
    'LT',
    'LU',
    'LV',
    'MA',
    'MC',
    'MT',
    'MX',
    'MY',
    'NI',
    'NL',
    'NO',
    'NZ',
    'OM',
    'PA',
    'PE',
    'PH',
    'PL',
    'PS',
    'PT',
    'PY',
    'QA',
    'RO',
    'SA',
    'SE',
    'SG',
    'SK',
    'SV',
    'TH',
    'TN',
    'TR',
    'TW',
    'US',
    'UY',
    'VN',
    'ZA' ],
 disc_number: 1,
 duration_ms: 208918,
 explicit: false,
 external_ids: { isrc: 'US-KMZ-09-50012' },
 external_urls:
  { spotify: 'https://open.spotify.com/track/7Gg8eAZ0t3pa22vDyVdAVV' },
 href: 'https://api.spotify.com/v1/tracks/7Gg8eAZ0t3pa22vDyVdAVV',
 id: '7Gg8eAZ0t3pa22vDyVdAVV',
 is_local: false,
 name: 'Bristol Nights',
 popularity: 7,
 preview_url:
  'https://p.scdn.co/mp3-preview/dc0a5d8e3d4668c4d71b8c44594ad21310b4cda0?cid=7c1864d3818042229a1abd512e54cbf8',
 track_number: 1,
 type: 'track',
 uri: 'spotify:track:7Gg8eAZ0t3pa22vDyVdAVV' }